export interface Recipe {
  id: number
  title: string
  image: string
  rating: number
  category: string
  region?: string
  description?: string
  prepTime?: string
  cookTime?: string
  servings?: number
  ingredients: string[]
  steps: string[]
}

export const recipes: Recipe[] = [
  {
    id: 1,
    title: "Avocado Toast with Poached Eggs",
    image: "https://www.aberdeenskitchen.com/wp-content/uploads/2019/05/Avocado-Egg-Breakfast-Toast-FI-Thumbnail-1200X1200.jpg?height=300&width=400",
    rating: 4.5,
    category: "Breakfast",
    description: "A nutritious breakfast option that's quick to prepare",
    prepTime: "10 mins",
    cookTime: "5 mins",
    servings: 2,
    ingredients: [
      "2 slices of whole grain bread",
      "1 ripe avocado",
      "2 eggs",
      "Salt and pepper to taste",
      "Red pepper flakes (optional)",
      "1 tbsp olive oil",
    ],
    steps: [
      "Toast the bread until golden and firm.",
      "While the bread is toasting, halve the avocado and remove the pit.",
      "Poach the eggs in simmering water for 3-4 minutes.",
      "Scoop the avocado onto the toast and mash it down with a fork.",
      "Top with poached eggs, salt, pepper, and red pepper flakes if desired.",
    ],
  },
  {
    id: 2,
    title: "Creamy Tomato Basil Pasta",
    image: "https://cdn.apartmenttherapy.info/image/upload/f_jpg,q_auto:eco,c_fill,g_auto,w_1500,ar_1:1/k%2Farchive%2F0eb929bc2c007ebf6009316a327b1e37587045a4?height=300&width=400",
    rating: 4.8,
    category: "Dinner",
    description: "A comforting pasta dish with rich tomato flavor",
    prepTime: "15 mins",
    cookTime: "20 mins",
    servings: 4,
    ingredients: [
      "8 oz pasta of choice",
      "2 tbsp olive oil",
      "3 cloves garlic, minced",
      "1 can (14 oz) diced tomatoes",
      "1/2 cup heavy cream",
      "1/4 cup fresh basil, chopped",
      "Salt and pepper to taste",
      "Grated parmesan for serving",
    ],
    steps: [
      "Cook pasta according to package instructions.",
      "In a large skillet, heat olive oil over medium heat.",
      "Add garlic and sauté until fragrant, about 30 seconds.",
      "Add diced tomatoes and simmer for 10 minutes.",
      "Stir in heavy cream and basil, then season with salt and pepper.",
      "Drain pasta and add to the sauce, tossing to coat.",
      "Serve with grated parmesan on top.",
    ],
  },
  {
    id: 3,
    title: "Dosa",
    image: "https://www.indianhealthyrecipes.com/wp-content/uploads/2023/06/brown-rice-dosa-recipe.jpg?height=300&width=400",
    rating: 4.9,
    category: "Breakfast",
    region: "Tamil Nadu",
    description: "A thin, crispy South Indian pancake made from fermented rice and lentil batter",
    prepTime: "8 hours (including fermentation)",
    cookTime: "20 mins",
    servings: 6,
    ingredients: [
      "2 cups rice",
      "1 cup urad dal (split black gram)",
      "1/4 tsp fenugreek seeds",
      "Salt to taste",
      "Water as needed",
      "Oil for cooking",
    ],
    steps: [
      "Wash and soak rice, urad dal, and fenugreek seeds separately for 4-5 hours.",
      "Grind urad dal to a smooth paste and rice to a slightly coarse paste.",
      "Mix both batters together, add salt, and let it ferment overnight (8-10 hours).",
      "Heat a non-stick pan or traditional dosa tawa.",
      "Pour a ladleful of batter and spread it in a circular motion to make a thin pancake.",
      "Drizzle oil around the edges and cook until golden brown and crisp.",
      "Fold and serve hot with sambar and coconut chutney.",
    ],
  },
  {
    id: 4,
    title: "Fresh Mediterranean Salad",
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTIYynBbeVAsxOLyEqoyJUHOydBidppiT_W9A&s?height=300&width=400",
    rating: 4.3,
    category: "Lunch",
    description: "A refreshing salad perfect for warm days",
    prepTime: "15 mins",
    cookTime: "0 mins",
    servings: 2,
    ingredients: [
      "2 cups mixed greens",
      "1 cucumber, diced",
      "1 cup cherry tomatoes, halved",
      "1/2 red onion, thinly sliced",
      "1/2 cup kalamata olives",
      "1/2 cup feta cheese, crumbled",
      "2 tbsp olive oil",
      "1 tbsp lemon juice",
      "1 tsp dried oregano",
      "Salt and pepper to taste",
    ],
    steps: [
      "In a large bowl, combine mixed greens, cucumber, tomatoes, red onion, olives, and feta cheese.",
      "In a small bowl, whisk together olive oil, lemon juice, oregano, salt, and pepper.",
      "Pour the dressing over the salad and toss gently to combine.",
      "Serve immediately or refrigerate for up to 1 hour before serving.",
    ],
  },
  {
    id: 5,
    title: "Idli",
    image: "https://5.imimg.com/data5/SELLER/Default/2023/3/296179680/PK/JO/EG/186596495/ready-made-idli-ready-to-eat-idly.jpeg?height=300&width=400",
    rating: 4.7,
    category: "Breakfast",
    region: "Tamil Nadu",
    description: "Soft, steamed rice cakes that are a staple breakfast in South India",
    prepTime: "8 hours (including fermentation)",
    cookTime: "15 mins",
    servings: 8,
    ingredients: [
      "2 cups idli rice or parboiled rice",
      "1 cup urad dal (split black gram)",
      "1/4 tsp fenugreek seeds",
      "Salt to taste",
      "Water as needed",
    ],
    steps: [
      "Wash and soak rice, urad dal, and fenugreek seeds separately for 4-5 hours.",
      "Grind urad dal to a smooth, fluffy paste and rice to a slightly coarse paste.",
      "Mix both batters together, add salt, and let it ferment overnight (8-10 hours).",
      "Grease idli molds and pour the batter into them.",
      "Steam in an idli steamer or pressure cooker (without whistle) for 10-12 minutes.",
      "Let them cool slightly, then remove from molds.",
      "Serve hot with sambar and coconut chutney.",
    ],
  },
  {
    id: 6,
    title: "Berry Smoothie Bowl",
    image: "https://www.tasteofhome.com/wp-content/uploads/2018/06/Berry-Smoothie-Bowl_EXPS_JMZ18_224489_B03_08_5b.jpg?height=300&width=400",
    rating: 4.6,
    category: "Breakfast",
    description: "A nutritious and colorful breakfast bowl",
    prepTime: "10 mins",
    cookTime: "0 mins",
    servings: 1,
    ingredients: [
      "1 cup frozen mixed berries",
      "1 banana",
      "1/2 cup Greek yogurt",
      "1/4 cup almond milk",
      "Toppings: granola, fresh berries, chia seeds, honey",
    ],
    steps: [
      "In a blender, combine frozen berries, banana, Greek yogurt, and almond milk.",
      "Blend until smooth and creamy. The mixture should be thick.",
      "Pour into a bowl.",
      "Top with granola, fresh berries, chia seeds, and a drizzle of honey.",
      "Serve immediately.",
    ],
  },
  {
    id: 7,
    title: "Sambar",
    image: "https://www.cubesnjuliennes.com/wp-content/uploads/2021/01/South-Indian-Sambar-Recipe.jpg?height=300&width=400",
    rating: 4.8,
    category: "Lunch",
    region: "Tamil Nadu",
    description: "A flavorful lentil-based vegetable stew, essential in South Indian cuisine",
    prepTime: "20 mins",
    cookTime: "40 mins",
    servings: 6,
    ingredients: [
      "1 cup toor dal (split pigeon peas)",
      "1 small eggplant, cubed",
      "2 medium tomatoes, chopped",
      "1 carrot, chopped",
      "10-12 drumsticks (moringa pods), cut into 3-inch pieces",
      "1 onion, chopped",
      "2 tbsp sambar powder",
      "1/2 tsp turmeric powder",
      "1 tsp tamarind paste",
      "Salt to taste",
      "For tempering: mustard seeds, curry leaves, dried red chilies, asafoetida",
    ],
    steps: [
      "Wash and pressure cook toor dal with turmeric until soft (about 4-5 whistles).",
      "In a pot, cook all vegetables with salt and turmeric until tender.",
      "Mash the cooked dal and add it to the vegetables.",
      "Add tamarind paste, sambar powder, and salt. Mix well and simmer for 5-7 minutes.",
      "For tempering, heat oil in a small pan, add mustard seeds, and when they splutter, add curry leaves, dried red chilies, and asafoetida.",
      "Pour the tempering over the sambar and mix well.",
      "Garnish with fresh coriander leaves and serve hot with rice, idli, or dosa.",
    ],
  },
  {
    id: 8,
    title: "Chettinad Chicken Curry",
    image: "https://www.whiskaffair.com/wp-content/uploads/2020/09/Chicken-Chettinad-Curry-2-3.jpg?height=300&width=400",
    rating: 4.9,
    category: "Dinner",
    region: "Tamil Nadu",
    description: "A fiery, aromatic chicken curry from the Chettinad region of Tamil Nadu",
    prepTime: "30 mins",
    cookTime: "45 mins",
    servings: 4,
    ingredients: [
      "1 kg chicken, cut into pieces",
      "2 large onions, finely chopped",
      "3 tomatoes, chopped",
      "2 tbsp ginger-garlic paste",
      "3-4 green chilies, slit",
      "2 tbsp Chettinad masala powder",
      "1 tsp turmeric powder",
      "1 tsp red chili powder",
      "1/2 cup coconut milk",
      "2 tbsp oil",
      "1 tsp fennel seeds",
      "1 cinnamon stick",
      "3-4 cloves",
      "3-4 cardamom pods",
      "1 star anise",
      "Curry leaves",
      "Salt to taste",
      "Coriander leaves for garnish",
    ],
    steps: [
      "Heat oil in a heavy-bottomed pan. Add fennel seeds, cinnamon, cloves, cardamom, and star anise. Sauté until fragrant.",
      "Add curry leaves and green chilies, followed by onions. Sauté until golden brown.",
      "Add ginger-garlic paste and sauté until the raw smell disappears.",
      "Add tomatoes and cook until they turn mushy.",
      "Add turmeric powder, red chili powder, Chettinad masala powder, and salt. Mix well.",
      "Add chicken pieces and mix to coat them with the masala. Cook for 5 minutes.",
      "Add 1 cup of water, cover, and cook on medium heat until the chicken is tender (about 25-30 minutes).",
      "Stir in coconut milk and simmer for 5 more minutes.",
      "Garnish with coriander leaves and serve hot with rice or parotta.",
    ],
  },
  {
    id: 9,
    title: "Pongal",
    image: "https://www.indianhealthyrecipes.com/wp-content/uploads/2021/01/pongal-ven-pongal.jpg?height=300&width=400",
    rating: 4.6,
    category: "Breakfast",
    region: "Tamil Nadu",
    description: "A comforting rice and lentil porridge, popular during the Pongal festival",
    prepTime: "10 mins",
    cookTime: "30 mins",
    servings: 4,
    ingredients: [
      "1 cup rice",
      "1/2 cup moong dal (yellow split lentils)",
      "2 tbsp ghee",
      "1 tsp cumin seeds",
      "1 tsp black pepper, crushed",
      "1/2 tsp asafoetida",
      "1 inch ginger, grated",
      "Few curry leaves",
      "2-3 green chilies, chopped",
      "1/4 cup cashew nuts",
      "Salt to taste",
    ],
    steps: [
      "Wash rice and moong dal together. Pressure cook them with 4 cups of water and salt until soft (about 4 whistles).",
      "In a pan, heat ghee and add cumin seeds, black pepper, and asafoetida.",
      "Add ginger, curry leaves, green chilies, and cashew nuts. Sauté until cashews turn golden.",
      "Add the cooked rice and dal mixture to the pan. Mix well.",
      "Adjust consistency by adding hot water if needed. The pongal should have a porridge-like consistency.",
      "Serve hot with coconut chutney and sambar.",
    ],
  },
  {
    id: 10,
    title: "Rasam",
    image: "https://www.indianhealthyrecipes.com/wp-content/uploads/2018/11/rasam-recipe.jpg?height=300&width=400",
    rating: 4.7,
    category: "Lunch",
    region: "Tamil Nadu",
    description: "A tangy, spicy soup that's both comforting and medicinal",
    prepTime: "15 mins",
    cookTime: "20 mins",
    servings: 4,
    ingredients: [
      "2 tbsp toor dal (split pigeon peas)",
      "2 medium tomatoes, chopped",
      "1 tbsp tamarind paste",
      "1 tsp rasam powder",
      "1/2 tsp turmeric powder",
      "1/2 tsp black pepper, crushed",
      "1 tsp cumin seeds, crushed",
      "2-3 green chilies, slit",
      "1 tbsp ghee or oil",
      "1 tsp mustard seeds",
      "Few curry leaves",
      "2 cloves garlic, crushed",
      "1 sprig coriander leaves, chopped",
      "Salt to taste",
    ],
    steps: [
      "Cook toor dal with turmeric until soft and mash it lightly.",
      "In a pot, cook tomatoes with a little water until soft.",
      "Add tamarind paste, rasam powder, salt, pepper, and cumin. Bring to a boil.",
      "Add the mashed dal and 2 cups of water. Simmer for 5 minutes.",
      "For tempering, heat ghee in a small pan, add mustard seeds, and when they splutter, add curry leaves, green chilies, and garlic.",
      "Pour the tempering over the rasam and garnish with coriander leaves.",
      "Serve hot as a soup or with rice.",
    ],
  },
  {
    id: 11,
    title: "Coconut Chutney",
    image: "https://www.indianhealthyrecipes.com/wp-content/uploads/2022/05/coconut-chutney-recipe.jpg?height=300&width=400",
    rating: 4.5,
    category: "Breakfast",
    region: "Tamil Nadu",
    description: "A classic accompaniment to South Indian breakfast items",
    prepTime: "10 mins",
    cookTime: "5 mins",
    servings: 4,
    ingredients: [
      "1 cup fresh coconut, grated",
      "2 green chilies",
      "1 inch ginger",
      "1 tbsp roasted chana dal (optional)",
      "Salt to taste",
      "Water as needed",
      "For tempering: oil, mustard seeds, urad dal, curry leaves, dried red chili",
    ],
    steps: [
      "Grind coconut, green chilies, ginger, roasted chana dal, and salt with a little water to make a smooth paste.",
      "Transfer to a serving bowl.",
      "For tempering, heat oil in a small pan, add mustard seeds, and when they splutter, add urad dal, curry leaves, and dried red chili.",
      "Pour the tempering over the chutney and mix well.",
      "Serve with idli, dosa, or vada.",
    ],
  },
  {
    id: 12,
    title: "Mutton Biryani (Tamil Nadu Style)",
    image: "https://www.hindustantimes.com/ht-img/img/2024/03/17/550x309/Chennai_Mutton_Biryani_1710659287055_1710659323008.jpg?height=300&width=400",
    rating: 4.9,
    category: "Dinner",
    region: "Tamil Nadu",
    description: "A flavorful rice dish with tender mutton pieces and aromatic spices",
    prepTime: "30 mins",
    cookTime: "1 hour",
    servings: 6,
    ingredients: [
      "500g mutton, cut into pieces",
      "3 cups basmati rice, soaked for 30 minutes",
      "3 large onions, thinly sliced",
      "2 tomatoes, chopped",
      "2 tbsp ginger-garlic paste",
      "4-5 green chilies, slit",
      "1/2 cup yogurt",
      "1/4 cup mint leaves",
      "1/4 cup coriander leaves",
      "2 tbsp biryani masala",
      "1 tsp red chili powder",
      "1 tsp turmeric powder",
      "1 tsp garam masala",
      "4 tbsp ghee",
      "Whole spices (cinnamon, cardamom, cloves, bay leaf)",
      "1/4 cup fried onions",
      "Saffron soaked in milk (optional)",
      "Salt to taste",
    ],
    steps: [
      "Marinate mutton with yogurt, ginger-garlic paste, red chili powder, turmeric, biryani masala, and salt for at least 1 hour.",
      "In a large pot, heat ghee and add whole spices. Sauté until fragrant.",
      "Add sliced onions and cook until golden brown.",
      "Add green chilies, tomatoes, and marinated mutton. Cook until the mutton is partially done (about 20 minutes).",
      "Add mint and coriander leaves.",
      "In another pot, cook the soaked rice until 70% done.",
      "Layer the partially cooked rice over the mutton mixture.",
      "Sprinkle fried onions and saffron milk on top.",
      "Cover with a tight lid and cook on low heat for 20-25 minutes.",
      "Mix gently before serving.",
    ],
  },
]
